services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore-sql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password1234@!'
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"Password1234@!\" -Q \"SELECT 1\" -C -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  gamestore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamestore-api
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=GameStore;User Id=sa;Password=Password1234@!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlserver_data:
